import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useReactMediaRecorder } from 'react-media-recorder';
import { useState } from 'react';

export default function Home() {
  const [audioFiles, setAudioFiles] = useState([]);
  const { status, startRecording, stopRecording, mediaBlobUrl } =
    useReactMediaRecorder({
      audio: true,
      onStop: (data) => setAudioFiles([...audioFiles, data]),
    });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Audio editor Proof of Concept</h1>
        <div>
          <p className={styles.description}>
            Let&apos;s start recording audio:
          </p>
          <p>{status}</p>
          <button onClick={startRecording}>Start Recording</button>
          <button onClick={stopRecording}>Stop Recording</button>
          <div>
            {audioFiles.length &&
              audioFiles.map((audioFile) => (
                <audio key={audioFile} src={audioFile} controls />
              ))}
          </div>
        </div>
      </main>
    </div>
  );
}
